### PR TITLE
fix: update dependencies and config files to latest format

### PR DESCRIPTION
**Pull request by LumaKernel**
Initial tasks:

- [x] Upgrade `@sveltejs/vite-plugin-svelte` with rewriting to `"@sveltejs/vite-plugin-svelte": "^1.0.0-next.14"`
- [x] Replace `const svelte = require('@sveltejs/vite-plugin-svelte')` to `const { svelte } = require('@sveltejs/vite-plugin-svelte')`.
- [x] Update `windicss` and `vite-plugin-windicss` in deps to latest major version.
- [x] Copy `svelte.config.js` from `minimal-ts` to `windicss-ts` for compiling `<script lang="ts">` correctly.
  - We can check this by trying `export let name: string;`.
- [x] Upgrade all dependencies declaration and lockfile by `pnpm update --filter=.`.
- [x] Upgrade vite with rewriting to `"vite": "^2.4.3"`
- [x] Upgrade esbuild with rewriting to `"esbuild": "^0.12.5"`
  - `vite@2.4.3` is depending on `esbuild@0.12.5` and they should be identical in order to work with manual postinstall in CI.
- [x] Vite config files are replaced in ESModule form.

After first look:

- [x] Use consistent version of windicss. ( I didn't upgrade on playgrounds. )
- [x] Use esm for other config files if possible.
- [x] Add `type: module` to package.json manifests.
- [x] Use `.cjs` for common js setting files if possible.
- [x] Use `cross-env NODE_OPTIONS=--experimental-vm-modules` for node option while running jest.
  - It's needed for running SSR tests that run `vite` with reading esm config file.

### CODE REVIEW

**Comment by LumaKernel** [comment]
Now test shows some warnings though all are passing.

<details>
<summary><code>pnpm --no-color test</code></summary>

<br />

```
> svite-monorepo@ test /home/luma/ghq/github.com/svitejs/svite
> run-s test:serve test:build


> svite-monorepo@ test:serve /home/luma/ghq/github.com/svitejs/svite
> cross-env NODE_OPTIONS=--experimental-vm-modules jest

(node:31767) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Determining test suites to run...
preparing non ci env...
syncing node_modules
syncing node_modules done
building packages

> svite-monorepo@ build:ci /home/luma/ghq/github.com/svitejs/svite
> pnpm -r build-bundle --filter=\!./packages/playground

Scope: 11 of 24 workspace projects
packages/svite build-bundle$ node scripts/build-bundle.js
│ bundling svite with esbuild
│   dist/cli/svite.js  4.1kb
│   dist/index.js      1.2kb
│ ⚡ Done in 3ms
└─ Done in 69ms
building packages done
preparations done
(node:32034) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32028) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
PASS packages/playground/svite-ssr/__tests__/svite-ssr.spec.ts

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      64 |         // always read fresh template in dev
      65 |         template = fs.readFileSync(resolve('index.html'), 'utf-8')
    > 66 |         template = await vite.transformIndexHtml(url, template)
         |                    ^
      67 |         render = (await vite.ssrLoadModule('/src/entry-server.js')).render
      68 |       } else {
      69 |         template = indexProd

      at node_modules/.pnpm/vite@2.4.3/node_modules/vite/src/node/plugins/html.ts:85:38
      at traverseHtml (node_modules/.pnpm/vite@2.4.3/node_modules/vite/src/node/plugins/html.ts:85:32)
      at devHtmlHook (node_modules/.pnpm/vite@2.4.3/node_modules/vite/src/node/server/middlewares/indexHtml.ts:91:3)
      at applyHtmlTransforms (node_modules/.pnpm/vite@2.4.3/node_modules/vite/src/node/plugins/html.ts:481:17)
      at temp/serve/svite-ssr/server.js:66:20

  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "TypeError: Cannot destructure property 'parse' of '(intermediate value)' as it is undefined.
        at traverseHtml (/home/luma/ghq/github.com/svitejs/svite/node_modules/.pnpm/vite@2.4.3/node_modules/vite/src/node/plugins/html.ts:85:11)
        at devHtmlHook (/home/luma/ghq/github.com/svitejs/svite/node_modules/.pnpm/vite@2.4.3/node_modules/vite/src/node/server/middlewares/indexHtml.ts:91:3)
        at applyHtmlTransforms (/home/luma/ghq/github.com/svitejs/svite/node_modules/.pnpm/vite@2.4.3/node_modules/vite/src/node/plugins/html.ts:481:17)
        at /home/luma/ghq/github.com/svitejs/svite/temp/serve/svite-ssr/server.js:66:20".

      83 |     } catch (e) {
      84 |       vite && vite.ssrFixStacktrace(e)
    > 85 |       console.log(e.stack)
         |               ^
      86 |       res.status(500).end(e.stack)
      87 |     }
      88 |   })

      at traverseHtml (node_modules/.pnpm/vite@2.4.3/node_modules/vite/src/node/plugins/html.ts:85:11)
      at devHtmlHook (node_modules/.pnpm/vite@2.4.3/node_modules/vite/src/node/server/middlewares/indexHtml.ts:91:3)
      at applyHtmlTransforms (node_modules/.pnpm/vite@2.4.3/node_modules/vite/src/node/plugins/html.ts:481:17)
      at temp/serve/svite-ssr/server.js:66:20".
      at console.log (node_modules/.pnpm/@jest/console@26.6.2/node_modules/@jest/console/build/BufferedConsole.js:197:10)
      at temp/serve/svite-ssr/server.js:85:15

PASS packages/playground/hmr/__tests__/hmr.spec.ts (5.121 s)

Test Suites: 2 passed, 2 total
Tests:       18 passed, 18 total
Snapshots:   0 total
Time:        5.778 s
Ran all test suites.

> svite-monorepo@ test:build /home/luma/ghq/github.com/svitejs/svite
> cross-env NODE_OPTIONS=--experimental-vm-modules VITE_TEST_BUILD=1 jest

(node:32334) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Determining test suites to run...
preparing non ci env...
syncing node_modules
syncing node_modules done
building packages

> svite-monorepo@ build:ci /home/luma/ghq/github.com/svitejs/svite
> pnpm -r build-bundle --filter=\!./packages/playground

Scope: 11 of 24 workspace projects
packages/svite build-bundle$ node scripts/build-bundle.js
│ bundling svite with esbuild
│   dist/cli/svite.js  4.1kb
│   dist/index.js      1.2kb
│ ⚡ Done in 3ms
└─ Done in 72ms
building packages done
preparations done
(node:32637) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32640) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
PASS packages/playground/svite-ssr/__tests__/svite-ssr.spec.ts
PASS packages/playground/hmr/__tests__/hmr.spec.ts

Test Suites: 2 passed, 2 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        3.852 s, estimated 6 s
Ran all test suites.
```

</details>

**Comment by dominikg** [comment]
jest esm still is very rough. best to keep that cjs for now. the tests also don't make much sense here since vite-plugin-svelte moved out of this repo.

reverting playground in this PR is fine I guess. most stuff in there is going to be removed anyways

**Comment by LumaKernel** [comment]
Hi. I reverted files in playground about esm module resolution. Unfortunately I'm still getting the same warnings though.

**Comment by dominikg** [comment]
i've added more updates and disabled tests for now. The existing tests were all meant to test vite-plugin-svelte which is no longer in this repo.

In a future PR, the tests can be reenabled and should test  templates instead.

**Comment by LumaKernel** [comment]
I've added 2 extra commits, first reverts my incomplete attempt to make svelte files in routing to typescript. Second fixes misconfigured svelte.config.js.

First one may be resolved after https://github.com/roxiness/routify/pull/386 🚀

**Comment by dominikg** [comment]
updated tsconfig, this is starting to look complete. Anything else you want to add?

**Comment by LumaKernel** [comment]
No. It's ready!

**Pull request merged**
